use_frameworks!

platform :ios, '8.0'

target 'MockAliTableView_Example' do
  pod 'MockAliTableView', :path => '../'

  target 'MockAliTableView_Tests' do
    inherit! :search_paths

#   pod 'Masonry'
#   pod 'MJRefresh'
  end
end
